[book]
authors = ["quambene"]
multilingual = false
src = "src"
title = "quambene's blog"

[output.html]
site-url = "/"
# git-repository-url = "https://github.com/quambene/blog"
default-theme = "light"
preferred-dark-theme = "navy"

[output.html.print]
enable = false
